# Container Linux Config
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQD0b7/p6r/OB0ETmuWANndHdVlFzDA1vSD0ByO6/wbcwiz8265oWajfmCmrEhTEG6WMX5RQWZ2L/56Sb+MlcZQpZp77QKikgyqpfJdHuyq1bAIvfbl9Z8Ms1zYQMjdlOVbdNxQV7F3eMoh7bFIoXsDiatbPxEf8H9TkJI1UaPT1Gw== core@example.com"
systemd:
  units:
    - name: var-lib-docker.mount
      enabled: true
      contents: |
        [Unit]
        Description=Mount /var/lib/docker
        [Mount]
        What=/dev/vg01/docker_vol
        Where=/var/lib/docker
        Type=ext4
        [Install]
        WantedBy=multi-user.target
    - name: docker.socket
      dropins:
        - name: 20-tcp-listen-stream.conf
          contents: |
            [Socket]
            ListenStream=2375
    - name: docker.service
      dropins:
        - name: 10-wait-docker.conf
          contents: |
            [Unit]
            After=docker.socket network.target var-lib-docker.mount etcd-member.service
            Requires=docker.socket var-lib-docker.mount etcd-member.service
        - name: 20-docker.conf
          contents: |
            [Service]
            Environment="DOCKER_OPTS=--log-driver=journald --cluster-store=etcd://localhost:2379 --cluster-advertise=ens192:2375"
    - name: settimezone.service
      enabled: true
      contents: |
        [Unit]
        Description=Set the time zone
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/timedatectl set-timezone Asia/Shanghai
        [Install]
        WantedBy=multi-user.target
    - name: etcd2-discovery-url.service
      enabled: true
      contents: |
        [Unit]
        Description=Set etcd discovery url from ovfEnv
        Requires=vmtoolsd.service
        After=vmtoolsd.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/usr/bin/echo 'Writing file to "/etc/etcd2.env"'
        ExecStart=/srv/setup-etcd2-discovery-env
        ExecStart=/usr/bin/echo 'Wrote file to "/etc/etcd2.env"'
        [Install]
        WantedBy=multi-user.target
    - name: etcd-member.service
      dropins:
        - name: 30-discovery.conf
          contents: |
            [Unit]
            Requires=etcd2-discovery-url.service
            After=etcd2-discovery-url.service
            [Service]
            EnvironmentFile=/etc/etcd2.env
    - name: advertise-swarm-node.service
      enabled: true
      contents: |
        [Unit]
        Description=Advertise this node as a docker swarm node
        Requires=docker.service etcd2.service
        After=docker.service etcd-member.service
        [Service]
        ExecStartPre=-/usr/bin/docker kill %p
        ExecStartPre=-/usr/bin/docker rm -v %p
        ExecStart=/usr/bin/docker run --rm --name %p \
            swarm \
            join \
            --advertise=$COREOS_PRIVATE_IPV4:2375 \
            etcd://$COREOS_PRIVATE_IPV4:2379
        ExecStop=/usr/bin/docker stop %p
        Restart=always
        RestartSec=10s
        TimeoutStartSec=120
        TimeoutStopSec=15
        [Install]
        WantedBy=multi-user.target
    - name: advertise-swarm-manager.service
      enabled: true
      contents: |
        [Unit]
        Description=Advertise this node as a docker swarm manager
        Requires=docker.service etcd2.service
        After=docker.service etcd-member.service
        [Service]
        ExecStartPre=-/usr/bin/docker kill %p
        ExecStartPre=-/usr/bin/docker rm -v %p
        ExecStart=/usr/bin/docker run --rm --name %p \
            -p 9999:2375 \
            swarm \
            manage \
            --replication \
            --advertise $COREOS_PRIVATE_IPV4:9999 \
            etcd://$COREOS_PRIVATE_IPV4:2379
        ExecStop=/usr/bin/docker stop %p
        Restart=always
        RestartSec=10s
        TimeoutStartSec=120
        TimeoutStopSec=15
        [Install]
        WantedBy=multi-user.target
etcd:
  initial_advertise_peer_urls: http://$COREOS_PRIVATE_IPV4:2380
  advertise_client_urls: http://$COREOS_PRIVATE_IPV4:2379,http://$COREOS_PRIVATE_IPV4:4001
  listen_peer_urls: http://0.0.0.0:2380
  listen_client_urls: http://0.0.0.0:2379,http://0.0.0.0:4001
  heartbeat_interval: 500
  election_timeout: 2500
locksmith:
  window_start: Fri 17:00
  window_length: 1h30m
  reboot_strategy: etcd-lock
update:
  group: stable
storage:
  files:
    - filesystem: "root"
      path: /srv/setup-etcd2-discovery-env
      mode: 0755
      user:
        name: root
      contents:
        inline: |
          #!/usr/bin/env sh
          ENV_FILE_PATH=/etc/etcd2.env
          
          LINE=$(/usr/share/oem/bin/vmtoolsd --cmd "info-get guestinfo.ovfEnv" | grep guestinfo.etcd.discovery.url)
          LINE=${LINE##*oe:value=}
          URL=${LINE%/>}
          echo ETCD_DISCOVERY=${URL} > ${ENV_FILE_PATH}
    - filesystem: "root"
      path: /srv/advertise-swarm-node
      mode: 0755
      user:
        name: root
      contents:
        inline: |
          #!/usr/bin/env sh
          
          /usr/bin/docker run --name swarm \
            --restart=unless-stopped \
            -d swarm \
            join \
            --advertise=$COREOS_PRIVATE_IPV4:2375 \
            etcd://$COREOS_PRIVATE_IPV4:2379
    - filesystem: "root"
      path: /srv/advertise-swarm-manager
      mode: 0755
      user:
        name: root
      contents:
        inline: |
          #!/bin/bash
          
          /usr/bin/docker run --name swarm-manager \
            --restart=unless-stopped \
            -p 9999:2375 \
            -d swarm \
            manage \
            --replication \
            --advertise $COREOS_PRIVATE_IPV4:9999 \
            etcd://$COREOS_PRIVATE_IPV4:2379
