#cloud-config
users:
  - name: core
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQD0b7/p6r/OB0ETmuWANndHdVlFzDA1vSD0ByO6/wbcwiz8265oWajfmCmrEhTEG6WMX5RQWZ2L/56Sb+MlcZQpZp77QKikgyqpfJdHuyq1bAIvfbl9Z8Ms1zYQMjdlOVbdNxQV7F3eMoh7bFIoXsDiatbPxEf8H9TkJI1UaPT1Gw== core@example.com
coreos:
  units:
    - name: settimezone.service
      command: start
      content: |
        [Unit]
        Description=Set the time zone
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/timedatectl set-timezone Asia/Shanghai
    - name: etcd2.service
      command: start
  etcd2:
    name: discovery0
    initial-cluster: discovery0=http://$private_ipv4:2380
    initial-advertise-peer-urls: http://$private_ipv4:2380
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    listen-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    initial-cluster-state: new
  update:
    reboot-strategy: etcd-lock
write_files:
  - path: /srv/get-cluster-token
    permissions: 0755
    owner: root
    content: |
      #!/usr/bin/env sh
      TOKEN_PATH="v2/keys/discovery"
      UUID="$(uuidgen)"
      
      curl -X PUT http://$private_ipv4:2379/${TOKEN_PATH}/${UUID}/_config/size -d value=3
      echo "ETCD_DISCOVERY=http://$private_ipv4:2379/${TOKEN_PATH}/${UUID}"
