#cloud-config
users:
  - name: core
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDkdp7+1EAwfTLlrJd10fKeLqedYh6qwlpXCtk3dtChqwxKNYvNxGJV7n34earmU0hxt26oqrXCLnp1OBlqO1SifKSqwr5+LIpz2uJxHA/wqVOMHmrzTlWMw8ljCBvDcQi323USt9IxqvO9WLICiVSujXYGReVcg9QGoyViAz1NTQ== core@example.com
coreos:
  units:
    - name: format-lvm.service
      command: start
      runtime: true
      content: |
        [Unit]
        Description=Format /dev/sdb
        Requires=dev-sdb.device
        After=dev-sdb.device
        ConditionFirstBoot=true
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/wipefs -f /dev/sdb
        ExecStart=/usr/sbin/pvcreate -f /dev/sdb
        ExecStart=/usr/sbin/vgcreate vg01 /dev/sdb
        ExecStart=/usr/sbin/lvcreate -L 99G --name docker_vol vg01
        ExecStart=/usr/sbin/mkfs.ext4 -f /dev/vg01/docker_vol
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount /var/lib/docker
        Requires=format-lvm.service
        After=format-lvm.service
        [Mount]
        What=/dev/vg01/docker_vol
        Where=/var/lib/docker
        Type=ext4
    - name: etcd2.service
      command: start
  etcd2:
    discovery: https://discovery.etcd.io/85634de10a3558819f5d4802171c9c32
    initial-advertise-peer-urls: http://$private_ipv4:2380
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    listen-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
