#cloud-config
users:
  - name: core
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQD0b7/p6r/OB0ETmuWANndHdVlFzDA1vSD0ByO6/wbcwiz8265oWajfmCmrEhTEG6WMX5RQWZ2L/56Sb+MlcZQpZp77QKikgyqpfJdHuyq1bAIvfbl9Z8Ms1zYQMjdlOVbdNxQV7F3eMoh7bFIoXsDiatbPxEf8H9TkJI1UaPT1Gw== core@example.com
coreos:
  units:
    - name: docker.service
      drop-ins:
        - name: 10-wait-docker.conf
          content: |
            [Unit]
            After=network.target etcd2.service
            Requires=etcd2.service
        - name: 20-docker.conf
          content: |
            [Service]
            Environment="DOCKER_OPTS=--log-driver=journald --registry-mirror=https://registry.docker-cn.com"
    - name: settimezone.service
      command: start
      content: |
        [Unit]
        Description=Set the time zone
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/timedatectl set-timezone Asia/Shanghai
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 30-discovery.conf
          content: |
            [Unit]
            [Service]
            EnvironmentFile=/etc/etcd2.env
  update:
    reboot-strategy: etcd-lock
  locksmith:
    window-start: Fri 17:00
    window-length: 1h30m

write_files:
  - path: /etc/etcd2.env
    permissions: 0655
    owner: root
content: |

